### ISSUE TITLE
[功能请求]机器人一次回复多条消息

### ISSUE THREAD

**Issue by Bamboo-D** [jie65535/mirai-console-jnr-plugin#10]
比如既回戳又回消息，被戳回复两张图 之类的。能不能实现 (*/ω＼*)

**Comment by jie65535** [comment]
#13 中已经实现戳回去的同时回复消息
回复两张图的情况，可以用电脑设置回复消息，在一条消息内包含多个图片即可，保存的是消息链，图文混合也可以。
