### ISSUE TITLE
希望加入更更复杂的解析

### ISSUE THREAD

**Issue by shigu666** [jie65535/mirai-console-jnr-plugin#16]
如题
如果设置为“#nudge test”，那么触发戳一戳并发送“test”
同理“#group.mute\:60 test”禁言60秒并发送test
“消息1\p消息2”发送消息1后发送消息2（即\p划分消息）

**Comment by jie65535** [comment]
带消息的特殊命令在之前的版本已经支持，见主页

- `#nudge` 戳回去
- `#nudge:戳我干嘛！` 戳回去，并且回复一条消息
- `#group.mute:30` 禁言30s, 可以自定义禁言时间, 单位秒
- `#group.mute:60:生气了！禁言你1分钟` 同上，并且回复一条消息

至于回复多条消息，不是很建议这么做，如果你希望回复多行的话，可以设置带换行的内容。
