### ISSUE TITLE
MCL无反应

### ISSUE THREAD

**Issue by RealSeek** [jie65535/mirai-console-jnr-plugin#2]
用的java11 mirai2.8.0 mcl1.2.2
插件放入plugins后正常生成配置文件
但使用/jnr无反应
无报错

**Comment by jie65535** [comment]
插件使用官方的指令系统，需要授权才可以使用指令，请检查相关权限。[参考文档](https://docs.mirai.mamoe.net/console/BuiltInCommands.html#permissioncommand)
或者，你也可以通过修改配置文件来设置预设回复。
