### ISSUE TITLE
希望加入回复语音的功能

### ISSUE THREAD

**Issue by SyuueenN** [jie65535/mirai-console-jnr-plugin#5]
目前在添加回复时回复语音，会提示成功，但不在 list 中也不会被触发。希望能加上这样的功能。
形式上除了直接发送语音，最好也可以直接发送录音文件。支持的格式只有 amr 不执行其他的转码也没关系。
谢谢！

**Comment by jie65535** [comment]
这个插件原理是把收到的回复消息序列化为MiraiCode，触发时又反序列化回来进行发送。

实际上没有保存相关的元数据文件，发送的应该都是缓存内容，所以我也不知道这是怎么处理的。

晚点我再研究一下吧。

**Comment by SyuueenN** [comment]
🆗，辛苦了
