### ISSUE TITLE
希望写个概率以随机到不回复，并且添加搓一搓的回复CD

### ISSUE THREAD

**Issue by damemod** [jie65535/mirai-console-jnr-plugin#7]
这样可以避免bot反复响应,甚至可以添加回复阈值，到一定阈值屏蔽多少时间(针对个人),(针对群体），总结:很专一的插件

**Comment by jie65535** [comment]
增加一个忽略比较简单，我加了一个关键字`#ignore`，但是戳一戳间隔的方案还得再想想
